require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TopStandingsController do

  # This should return the minimal set of attributes required to create a valid
  # TopStanding. As you add validations to TopStanding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TopStandingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all top_standings as @top_standings" do
      top_standing = TopStanding.create! valid_attributes
      get :index, {}, valid_session
      assigns(:top_standings).should eq([top_standing])
    end
  end

  describe "GET show" do
    it "assigns the requested top_standing as @top_standing" do
      top_standing = TopStanding.create! valid_attributes
      get :show, {:id => top_standing.to_param}, valid_session
      assigns(:top_standing).should eq(top_standing)
    end
  end

  describe "GET new" do
    it "assigns a new top_standing as @top_standing" do
      get :new, {}, valid_session
      assigns(:top_standing).should be_a_new(TopStanding)
    end
  end

  describe "GET edit" do
    it "assigns the requested top_standing as @top_standing" do
      top_standing = TopStanding.create! valid_attributes
      get :edit, {:id => top_standing.to_param}, valid_session
      assigns(:top_standing).should eq(top_standing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TopStanding" do
        expect {
          post :create, {:top_standing => valid_attributes}, valid_session
        }.to change(TopStanding, :count).by(1)
      end

      it "assigns a newly created top_standing as @top_standing" do
        post :create, {:top_standing => valid_attributes}, valid_session
        assigns(:top_standing).should be_a(TopStanding)
        assigns(:top_standing).should be_persisted
      end

      it "redirects to the created top_standing" do
        post :create, {:top_standing => valid_attributes}, valid_session
        response.should redirect_to(TopStanding.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved top_standing as @top_standing" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopStanding.any_instance.stub(:save).and_return(false)
        post :create, {:top_standing => { "title" => "invalid value" }}, valid_session
        assigns(:top_standing).should be_a_new(TopStanding)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopStanding.any_instance.stub(:save).and_return(false)
        post :create, {:top_standing => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested top_standing" do
        top_standing = TopStanding.create! valid_attributes
        # Assuming there are no other top_standings in the database, this
        # specifies that the TopStanding created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TopStanding.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => top_standing.to_param, :top_standing => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested top_standing as @top_standing" do
        top_standing = TopStanding.create! valid_attributes
        put :update, {:id => top_standing.to_param, :top_standing => valid_attributes}, valid_session
        assigns(:top_standing).should eq(top_standing)
      end

      it "redirects to the top_standing" do
        top_standing = TopStanding.create! valid_attributes
        put :update, {:id => top_standing.to_param, :top_standing => valid_attributes}, valid_session
        response.should redirect_to(top_standing)
      end
    end

    describe "with invalid params" do
      it "assigns the top_standing as @top_standing" do
        top_standing = TopStanding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopStanding.any_instance.stub(:save).and_return(false)
        put :update, {:id => top_standing.to_param, :top_standing => { "title" => "invalid value" }}, valid_session
        assigns(:top_standing).should eq(top_standing)
      end

      it "re-renders the 'edit' template" do
        top_standing = TopStanding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopStanding.any_instance.stub(:save).and_return(false)
        put :update, {:id => top_standing.to_param, :top_standing => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested top_standing" do
      top_standing = TopStanding.create! valid_attributes
      expect {
        delete :destroy, {:id => top_standing.to_param}, valid_session
      }.to change(TopStanding, :count).by(-1)
    end

    it "redirects to the top_standings list" do
      top_standing = TopStanding.create! valid_attributes
      delete :destroy, {:id => top_standing.to_param}, valid_session
      response.should redirect_to(top_standings_url)
    end
  end

end
